### ISSUE TITLE
Upgrade to .NETv8

### ISSUE THREAD

**Issue by neo-jp** [stefan-d-p/odc-jsonata-library#1]
Hi Stefan.

This library is using a runtime version that will be discontinued on Dec 20, 2024.
Are you able to upgrade this code?

Best Regards,
JP

**Comment by stefan-d-p** [comment]
Hi. Yes, i will shortly update the framework and release it to the forge.

**Comment by stefan-d-p** [comment]
I just submitted a new version to Forge. It is now in Pending Approval state, but should be available soon to update.
